<?php require("index.php"); ?>
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            CV
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    </head>
    <body id="cv" class="<">
        <header>
            <h1><?= $tab["nom"]; ?> <?= $tab["prenom"]; ?></h1>
            <h2>Intitulé du poste</h2>
        </header>
        <main>
            <section id="left">
                <h3>Informations</h3>
                <section>
                    <h4>
                        Contact
                    </h4>
                    <dl>
                        <dt>
                            Email
                        </dt>
                        <dd>
                            <?= $tab["email"]; ?>
                        </dd>
                        <dt>
                            Téléphone
                        </dt>
                        <dd>
                            <?= $tab["telephone"]; ?>
                        </dd>
                        <dt>
                            LinkedIn
                        </dt>
                        <dd>
                            <a href="<?= $tab["linkedin"]; ?>"><?= $tab["linkedin"]; ?></a>
                        </dd>
                        <dt>
                            GitHub
                        </dt>
                        <dd>
                            <a href="<?= $tab["github"]; ?>"><?= $tab["github"]; ?></a>
                        </dd>
                    </dl>
                </section>
                <section>
                    <h4>Biographie</h4>
                    <p>
                        <?= $tab["biographie"]; ?>
                    </p>
                </section>
                <section>
                    <h4>Loisirs</h4>
                    <ul>
                        <li>
                            <?= $tab2["loisir-1"]; ?>
                        </li>
                        <li>
                            <?= $tab2["loisir-2"]; ?>
                        </li>
                        <li>
                            <?= $tab2["loisir-3"]; ?>
                        </li>
                        <li>
                            <?= $tab2["loisir-4"]; ?>
                        </li>
                    </ul>
                </section>
            </section>
            <section id="right">
                <h3>Compétences</h3>
                <section>
                    <h4>Langages des programmation</h4>
                    <ul>
                        <?php foreach($tab["lang"] as $lang) { ?>
                        
                            <li><?= $lang; ?></li>
                        
                        <?php }; ?>
                    </ul>
                </section>
                <section>
                    <h4>Frameworks & Librairies</h4>
                    <ul>
                        <?php foreach($tab["frameworks"] as $framework) { ?>
                        
                            <li><?= $framework; ?></li>
                        
                        <?php } ?>
                    </ul>
                </section>
                <section>
                    <h4>Logiciels</h4>
                    <ul>
                        <?php foreach($tab["software"] as $software) { ?>
                        
                            <li><?= $software; ?></li>
                        
                        <?php } ?>
                    </ul>
                </section>
                <section>
                    <h4>Langues</h4>
                    <ul>
                        <?php
                        
                            foreach($tab["language"] as $language) { ?>
                        
                            <li><?= $language; ?></li>
                        
                        <?php } ?>
                    </ul>
                </section>
            </section>
        </main>
    </body>
</html>