<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8" />
        <title>
            Formulaire
        </title>
        <link rel="preconnect" href="https://fonts.googleapis.com">
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
        <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@200;400;600;800&display=swap" rel="stylesheet">
    </head>
    <body id="form">
        <main>
            <form method="post" action="cv.phtml">
                <?php 
            require("info.phtml");
            require("langs.phtml");
            require("prog.phtml");
            require("frame.phtml"); 
            require("logiciel.phtml");
            require("color.phtml"); 
            ?>
            
                <input type="submit" value="Envoyer" />
            </form>
        </main>
    </body>
</html>